Repository RentadroneCL/ui, pull requests merged in 2020-10, with the labels that each got.

#19 Update README.md
  README.md
Labels: documentation

#21 update dependencies
  composer.lock
  yarn.lock
Labels: dependencies

#23 Generating resources that transform individual models
  app/Http/Resources/Media.php
  app/Http/Resources/MediaCollection.php
  app/Http/Resources/Project.php
  routes/api.php
  routes/web.php
Labels: difficulty: medium, enhancement, good first issue, help wanted
